### ISSUE TITLE
More verbose error logging + better error handling

### ISSUE THREAD

**Issue by tejashah88** [mreinstein/alexa-verifier#17]
Looking at #16, it would make sense to rewrite some of the error logs to be a bit more verbose. [For example](https://github.com/mreinstein/alexa-verifier/blob/master/index.js#L101), the current message is a bit ambiguous (`'certificate verification failed'`), whereas the real reason the verification failed is due to a mismatch with signatures (`'certificate verification failed due to invalid signature'`?). Obviously it's debatable as to what is defined as "verbose enough", but IMHO, it should be just enough to not be too technical and not too vague as well. If needed, a flag can be passed to enable more verbose logging.

Another thing to note is the slight inconsistency with what the individual functions return. For example, [`validateTimestamp`](https://github.com/mreinstein/alexa-verifier/blob/master/index.js#L88) returns a string with the error message. However,  [`validateSignature`](https://github.com/mreinstein/alexa-verifier/blob/master/index.js#L99) returns a boolean that is later on used to return an error message to the `callback` if applicable. A possible change could be something like the following:

```javascript
// returns true if the signature for the request body is valid, false otherwise
function validateSignature(pem_cert, signature, requestBody) {
  var verifier
  verifier = crypto.createVerify('RSA-SHA1')
  verifier.update(requestBody)
  if (verifier.verify(pem_cert, signature, SIGNATURE_FORMAT)) {
    return null
  } else {
    return 'certificate verification failed due to invalid signature'
  }
}
```

The last thing I noticed is that if you don't supply a `callback` parameter, then [an empty function](https://github.com/mreinstein/alexa-verifier/blob/master/index.js#L83) is given. Unfortunately, this means that any errors that occur will be discarded and never see the light of day. It might be best to either leave a note in the README about this behavior or have the default `callback` function print all errors occurred. (`callback = function(er) { console.error(er) }`?).

**Comment by mreinstein** [comment]
thanks @tejashah88  closed via https://github.com/mreinstein/alexa-verifier/commit/cde450b90078b52eb45a5e865f3083d30fa382da
