### ISSUE TITLE
verification fails with double-byte utf-8 encodings

### ISSUE THREAD

**Issue by l33way** [mreinstein/alexa-verifier#19]
the verification will fail anytime the request contains double byte utf-8 encodings.
I believe that all requests from Alexa are UTF-8 encoded.

for example if the request contains the word "déjà vu"..  validation will fail.

this seems to fix the issue:

// returns true if the signature for the request body is valid, false otherwise
function isValidSignature(pem_cert, signature, requestBody) {
  ...
  verifier.update(requestBody);   // this line can be modified to:  verifier.update(requestBody,'utf8');
  ...
}

**Comment by mreinstein** [comment]
@l33way looks reasonable. Can you send a pull request please?

**Comment by l33way** [comment]
@mreinstein sure

**Comment by mreinstein** [comment]
thanks for the PR!
