### ISSUE TITLE
Alexa-App-Server?

### ISSUE THREAD

**Issue by arch1v1st** [mreinstein/alexa-verifier#2]
Hi,

I tried a variety of ways to get this working with Alexa-App-Server.  I suspect its possible to add a file to Alexa-App-Server's 'server/' directory, and tap into 'express.use' (reference [login.js example](https://www.npmjs.com/package/alexa-app-server#dynamic-server-side-functionality)), but all attempts thus far have failed.

Would you kindly share an example of how to leverage alexa-verifier with Alexa-App-Server for each request?

TIA!

**Comment by mreinstein** [comment]
@arch1v1st sorry for the reply delay. I think this is something that could be integrated into alexa-app-server as a new feature. Perhaps you could open an issue on that project and request inclusion: 

https://github.com/matt-kruse/alexa-app-server
