### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by EkiSkyten** [mreinstein/alexa-verifier#3]
I am getting an exception trying to verify the certificate chain.  Below is the stack trace.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at Socket._writeGeneric (net.js:681:26)
    at Socket._write (net.js:700:8)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Socket.Writable.write (_stream_writable.js:214:11)
    at Socket.write (net.js:626:40)
    at Object.module.exports.getCertificateInfo (C:\dev\alexa\node_modules\alexa-verifier\node_modules\openssl-cert-tools\lib\information.js:88:18)
    at validateCert (C:\dev\alexa\node_modules\alexa-verifier\index.js:77:18)
    at C:\dev\alexa\node_modules\alexa-verifier\index.js:49:18
    at Request._callback (C:\dev\alexa\node_modules\alexa-verifier\index.js:67:16)
    at Request.self.callback (C:\dev\alexa\node_modules\alexa-verifier\node_modules\request\request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\dev\alexa\node_modules\alexa-verifier\node_modules\request\request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\dev\alexa\node_modules\alexa-verifier\node_modules\request\request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)

**Comment by mreinstein** [comment]
can you provide more context? What environment are you running? How is this library getting invoked? EPIPE usually has something to do with an http connection closing.

**Comment by mreinstein** [comment]
search for EPIPE  

https://nodejs.org/dist/latest-v6.x/docs/api/errors.html

**Comment by EkiSkyten** [comment]
This is on WIndows 10 and node.js and alexa-app and alexa-app-server.

I just got up, so I have not had a chance to verify this yet.  But, I have a hypothesis:

I did put in some debug logging statements, and I noticed there were two certificates that came down from amazon. And so, was wondering if the code is setup for one certificate, and then exiting, if that is causing the exception?

**Comment by EkiSkyten** [comment]
One cert is from Amazon.
The other cert is from symantec

-----BEGIN CERTIFICATE-----
MIIE3zCCA8egAwIBAgIQOB+1EaEj3G47NDZlLK1cqzANBgkqhkiG9w0BAQsFADB+
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVj
IENsYXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MB4XDTE1MTAwNjAwMDAwMFoX
DTE2MTAzMDIzNTk1OVowbTELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0
b24xEDAOBgNVBAcMB1NlYXR0bGUxGTAXBgNVBAoMEEFtYXpvbi5jb20sIEluYy4x
HDAaBgNVBAMME2VjaG8tYXBpLmFtYXpvbi5jb20wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQCOoFGqSu4ZF1Dk4+xsjfJkMwz2Lf+gG598pNgLCt6HOxPf
oXZBNrcHpg86EsxtyV0BpeR98af15c8tztpUIfSs90/lIjJ0KDBpB0q3Rc0lqzwQ
5GTYlGaKdaNe9GhzwYHP12100+Yu0fKnVUxnqnqYytpph9X45fEyWwk9Tir5qn/i
UZtwYoULDbHe9wEOai4/izyY7VtMvnX1hf/n41OdsFRhFidN0FiTM5bM4h1+OQMe
7L8m9uUJiHr6uPHYTsV3Ell6fDYzQ4iUIUoq6+EOx8/R6eaPNRj4jyjtcs6m8QZX
S6EhrcbO7oRjZ2Q8FqLfXnJXxsq8JPfNl8+ews/9AgMBAAGjggFoMIIBZDAeBgNV
HREEFzAVghNlY2hvLWFwaS5hbWF6b24uY29tMAkGA1UdEwQCMAAwDgYDVR0PAQH/
BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBhBgNVHSAEWjBY
MFYGBmeBDAECAjBMMCMGCCsGAQUFBwIBFhdodHRwczovL2Quc3ltY2IuY29tL2Nw
czAlBggrBgEFBQcCAjAZGhdodHRwczovL2Quc3ltY2IuY29tL3JwYTAfBgNVHSME
GDAWgBRfYM9hkFXfhEMUimAqsvV69EMY7zArBgNVHR8EJDAiMCCgHqAchhpodHRw
Oi8vc3Muc3ltY2IuY29tL3NzLmNybDBXBggrBgEFBQcBAQRLMEkwHwYIKwYBBQUH
MAGGE2h0dHA6Ly9zcy5zeW1jZC5jb20wJgYIKwYBBQUHMAKGGmh0dHA6Ly9zcy5z
eW1jYi5jb20vc3MuY3J0MA0GCSqGSIb3DQEBCwUAA4IBAQAriLgemeyLMGSUjtm9
1iZtN1SAKJQJLj3lzP3R4bUotCqjfLy9SmhQoLunBxvzDZ3XNaz5HxZi04MyRh4Y
a3hURiizlFySPfbUXS2pUaRaH7iD3GACwFigVlBIzu3cV372fmPB5F0pwiM5WAZq
waE1PM323qcRn36x17mmR47kYbqobe0m7bEW5kmo/cWKBBwnJpJn0L5d0YPW2BHi
KbWNaO1TspcsTHOsdxBglxHLNgm+Ng7nNsJ7GWD0UOexR0XqPhXMXPyWQARd4z5L
QAffrhZ5Bq6ZmeLRegG3MldSCRohHVSvzLlKFikrPJ66tkWmey3D8YnghYx/+7XQ
HmbQ
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFODCCBCCgAwIBAgIQUT+5dDhwtzRAQY0wkwaZ/zANBgkqhkiG9w0BAQsFADCB
yjELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL
ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJp
U2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxW
ZXJpU2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0
aG9yaXR5IC0gRzUwHhcNMTMxMDMxMDAwMDAwWhcNMjMxMDMwMjM1OTU5WjB+MQsw
CQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAdBgNV
BAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVjIENs
YXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAstgFyhx0LbUXVjnFSlIJluhL2AzxaJ+aQihiw6UwU35VEYJb
A3oNL+F5BMm0lncZgQGUWfm893qZJ4Itt4PdWid/sgN6nFMl6UgfRk/InSn4vnlW
9vf92Tpo2otLgjNBEsPIPMzWlnqEIRoiBAMnF4scaGGTDw5RgDMdtLXO637QYqzu
s3sBdO9pNevK1T2p7peYyo2qRA4lmUoVlqTObQJUHypqJuIGOmNIrLRM0XWTUP8T
L9ba4cYY9Z/JJV3zADreJk20KQnNDz0jbxZKgRb78oMQw7jW2FUyPfG9D72MUpVK
Fpd6UiFjdS8W+cRmvvW1Cdj/JwDNRHxvSz+w9wIDAQABo4IBYzCCAV8wEgYDVR0T
AQH/BAgwBgEB/wIBADAwBgNVHR8EKTAnMCWgI6Ahhh9odHRwOi8vczEuc3ltY2Iu
Y29tL3BjYTMtZzUuY3JsMA4GA1UdDwEB/wQEAwIBBjAvBggrBgEFBQcBAQQjMCEw
HwYIKwYBBQUHMAGGE2h0dHA6Ly9zMi5zeW1jYi5jb20wawYDVR0gBGQwYjBgBgpg
hkgBhvhFAQc2MFIwJgYIKwYBBQUHAgEWGmh0dHA6Ly93d3cuc3ltYXV0aC5jb20v
Y3BzMCgGCCsGAQUFBwICMBwaGmh0dHA6Ly93d3cuc3ltYXV0aC5jb20vcnBhMCkG
A1UdEQQiMCCkHjAcMRowGAYDVQQDExFTeW1hbnRlY1BLSS0xLTUzNDAdBgNVHQ4E
FgQUX2DPYZBV34RDFIpgKrL1evRDGO8wHwYDVR0jBBgwFoAUf9Nlp8Ld7LvwMAnz
Qzn6Aq8zMTMwDQYJKoZIhvcNAQELBQADggEBAF6UVkndji1l9cE2UbYD49qecxny
H1mrWH5sJgUs+oHXXCMXIiw3k/eG7IXmsKP9H+IyqEVv4dn7ua/ScKAyQmW/hP4W
Ko8/xabWo5N9Q+l0IZE1KPRj6S7t9/Vcf0uatSDpCr3gRRAMFJSaXaXjS5HoJJtG
QGX0InLNmfiIEfXzf+YzguaoxX7+0AjiJVgIcWjmzaLmFN5OUiQt/eV5E1PnXi8t
TRttQBVSK/eHiXgSgW7ZTaoteNTCLD0IX4eRnh8OsN4wUmSGiaqdZpwOdgyA8nTY
Kvi4Os7X1g8RvmurFPW9QaAiY4nxug9vKWNmLT+sjHLF+8fk1A/yO0+MKcc=
-----END CERTIFICATE-----

Common Name: echo-api.amazon.com
Subject Alternative Names: echo-api.amazon.com
Organization: Amazon.com, Inc.
Locality: Seattle
State: Washington
Country: US
Valid From: October 5, 2015
Valid To: October 30, 2016
Issuer: Symantec Class 3 Secure Server CA - G4, Symantec Corporation Write review of Symantec
Serial Number: 381fb511a123dc6e3b3436652cad5cab

---------------------------------------------------------------------

Certificate Information:
Common Name: Symantec Class 3 Secure Server CA - G4
Subject Alternative Names: DirName: CN = SymantecPKI-1-534
Organization: Symantec Corporation
Organization Unit: Symantec Trust Network
Country: US
Valid From: October 30, 2013
Valid To: October 30, 2023
Issuer: VeriSign Class 3 Public Primary Certification Authority - G5, VeriSign, Inc. Write review of Symantec
Serial Number: 513fb9743870b73440418d30930699ff

----------------------------------------------------------------------------

This is most likely the problem.  Because the openssl code is throwing an exception and that is closing the pipe.

Need to make sure that only one cert is being passed to information.js validation code

**Comment by EkiSkyten** [comment]
Found real problem.  Environmental problem with openssl not found.

**Comment by mreinstein** [comment]
I think this may be a dupe of #1 Pull request welcome if you find a way to get this working cross platform. :)

**Comment by EkiSkyten** [comment]
Two pitfalls I ran into with windows 10:  openSSL wanted to be in a folder named c:\OpenSSL.  Then. the tool needed to write the temporary certificate it creates in c:\tmp.  Fixing these made everything work.
