### ISSUE TITLE
add promise support

### ISSUE THREAD

**Issue by mreinstein** [mreinstein/alexa-verifier#35]
if invoked without a callback function (e.g., `verifier(cert_url, signature, requestBody)` return a promise.

**Comment by tejashah88** [comment]
I'd suggest that a separate module should be made, so that we can keep the bloat out and it'll be a lot easier for maintaining the module itself, since the "promised" version would simple have to simply wrap this module in a resolve/reject statement. What do you think?

**Comment by mreinstein** [comment]
I think it's not necessary to make a seperate module. If we wanted to add new functionality or really change it's behavior I'd say a new module might be appropriate.

In this case, we're talking about moving away from callbacks torwards promises. This is something happening in the core ecosystem, now that `async`/`await` has landed in a stable LTS release. Eventually old versions of node that don't support remove promises natively will go away (2020-ish?) and the callback usage could be removed at that point.

I don't think it would add that much bloat to things. essentially some simple logic:

```
if (no callback specified)
   return new Promise(function( resolve, reject) { ... })

normal logic here
```
