### ISSUE TITLE
Timeouts downloading cert from behind proxy

### ISSUE THREAD

**Issue by kyle-wrenn** [mreinstein/alexa-verifier#44]
I'm getting timeouts when the module tries to download the certificate from S3. This is due to my corporate proxy. Other than forking and updating the configuration for https, do you have any suggestions?

**Comment by mreinstein** [comment]
can you vpn or otherwise tunnel around the proxy?

**Comment by kyle-wrenn** [comment]
Unfortunately, no. It looks like if the [request](https://github.com/request/request) module were used then my https_proxy env variable would be respected, but the https module does not.

**Comment by mreinstein** [comment]
I would suggest talking to whomever is in charge of your internal network and having them allow you to make https requests, or at least whitelist that amazon domain.  This module is intended to be used on public facing web servers that host alexa skills.

**Comment by kyle-wrenn** [comment]
I've opened a pull request to add some flexibility for those with the http_proxy setting enabled.
