### ISSUE TITLE
Update to Alexa Certificate

### ISSUE THREAD

**Issue by owise1** [mreinstein/alexa-verifier#58]
Hi,

Sorry if this is an ignorant question.  I received a notification from Amazon regarding an update to their certificate. Will this module continue to work after the switch? Or is there something else I need to do one my end.

> We  are replacing the certificate that Alexa uses to sign https requests on June 28, 2018. To ensure that your skill will continue to operate uninterrupted, please verify that: 
> * Your endpoint certificate checks are not pinned in code.
> * Your endpoint accepts of the Amazons Trust Services Certificate Authority (CA).
> * You are following the guidelines outlined in our technical documentation.

**Comment by owise1** [comment]
Here's the entire email:

> Verify Proper Certificate Validation in Your Alexa HTTPS Skill Endpoint
>  
> You are receiving this message because you have published an Alexa skill that uses an https endpoint. We are replacing the certificate that Alexa uses to sign https requests on June 28, 2018. To ensure that your skill will continue to operate uninterrupted, please verify that: 
> * Your endpoint certificate checks are not pinned in code.
> * Your endpoint accepts of the [Amazons Trust Services Certificate Authority (CA)](https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/?mkt_tok=eyJpIjoiTldFNE9ERTBaR1kyWkRRNCIsInQiOiJHVlR0R0gwa29FOVdjTVQyOXFzSHhhWEM5Y0xQVkxkTmsreEhuMjJvcitiQzgxa1JTZnJMUVhDR0swSUNpRjdaWXhJc0hRclRKT1dcL3diUnd3M2FCcTFuMUFMSG5ZYW5lOVNtZUx5V2R3VmNuYjhGTW1kUXFFcTdBckZXR0tCSGUifQ%3D%3D).
> * You are following the guidelines outlined in our technical documentation.Please ensure that your endpoint follows the instructions above by June 28, 2018. If it does not, customer interactions with your skill will fail.
> 
>

**Comment by mreinstein** [comment]
As far as I can tell this Amazon change should not affect the operation of this module. If you run into any problems though, please do let me know. Thanks for the heads-up!
