### ISSUE TITLE
This one mention Signature what is the meaning of this

### ISSUE THREAD

**Issue by hemantha** [mreinstein/alexa-verifier#59]
According to the program we have to pass Signature, What is that mean. From where can I extracted this value. Do I want to generate this. Really confuse this. I have a ssl certificate get from ACM.

**Comment by mreinstein** [comment]
are you using expressjs to host your alexa skill? If so, you should use this middleware: https://github.com/alexa-js/alexa-verifier-middleware

It's higher level and easier to integrate.
