### ISSUE TITLE
What is signature and where can I generate or assign

### ISSUE THREAD

**Issue by hemantha** [mreinstein/alexa-verifier#60]
Sorry if this is a lame question because I am new to this aws field anyway  Use of this we have to pass vairaboes as cert_url and signature. 
When we can use https://s3.amazonaws.com/echo.api/echo-api-cert.pem as a cert_url 
but I have a question where can I get the signature or how can I generate or assign.

**Comment by mreinstein** [comment]
Are you using expressjs to host your skill? If so this is probably what you want: https://github.com/alexa-js/alexa-verifier-middleware

`alexa-verifier` is a lower level validation function for people directly implementing a skill in some node web service. Better to use a higher level library.

**Comment by mreinstein** [comment]
even if you aren't using expressjs, `alexa-verifier-module` is a good starting point for understanding how to use `alexa-verifier` directly, if you still intend to.
