### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by fildanrcs** [mreinstein/alexa-verifier#61]
I've tries personally but there are also other references searching in internet which states this.

It ends always in 'invalid signature' error.

**Comment by mreinstein** [comment]
@fildanrcs I don't understand your issue. Can you provide more details please?

**Comment by mreinstein** [comment]
issue unclear, please elaborate on what issue you are running into and we'll re-open as needed.

**Comment by fildanrcs** [comment]
Sorry, I've updated the issue description.

**Comment by mreinstein** [comment]
I suspect your problem is in `let requestRawBody = JSON.stringify(request.body);`.

Stringifying the request body is not the same as the raw body input. You need the raw, unaltered request body (before any middlewares parse this into an object.)

Which server framework are you using?

**Comment by fildanrcs** [comment]
I'm using Azure Functions, so I fear I've no control on the middleware underneath.
Unfortunately I can't change this stack..

Do you have any other idea on how make the signature check by using the body in json format?

Thanks for the reply

**Comment by mreinstein** [comment]
You're going to need raw request body to use this. Perhaps this is already available via `request.rawBody` ? 

https://github.com/Azure/azure-functions-host/issues/293
https://github.com/Azure/azure-functions-host/issues/1951

**Comment by fildanrcs** [comment]
Works perfectly.. It was my bad :) 
Thanks a lot!

**Comment by mreinstein** [comment]
glad it worked!

**Comment by fildanrcs** [comment]
Yep. I have to admit that I was fooled by this [thread](https://webcache.googleusercontent.com/search?q=cache:_CIKMeossD8J:https://forums.developer.amazon.com/questions/7214/example-node-js-code-for-checking-the-signature-of.html+&cd=2&hl=en&ct=clnk&gl=it) since I'm using Azure Functions based on Windows.

Wanted just to clarify the original mistake.

Regards

**Comment by mreinstein** [comment]
thanks for the clarification. Perhaps this issue will be useful to others trying the same thing (which is why I renamed your original title.)
