### ISSUE TITLE
The skill end-point is not accepting valid signed requests.

### ISSUE THREAD

**Issue by Aynumi** [mreinstein/alexa-verifier#63]
Hosting skill on Heroku always receiving this last issue. I've tried using both this verifier and the alexa-verifier-middleware but no luck.

**Comment by mreinstein** [comment]
I don't have enough detail here to be able to help you. Can you provide some code that shows how you are integrating this module?

**Comment by mreinstein** [comment]
@Aynumi this feedback isn't actionable. If you get me more details we can re-open this issue.
