### ISSUE TITLE
Certificate check fails when requests originate from the Alexa Developer Console

### ISSUE THREAD

**Issue by juliaqiuxy** [mreinstein/alexa-verifier#64]
This is a follow-up to my issue reported on alexa/alexa-skills-kit-sdk-for-nodejs/issues/533

I'm using alexa-verifier to handle signature verification. But checks are failing when requests originate from the Alexa Developer Console.

I'm not sure if this issue is related to alexa-verifier or Alexa backend. Alexa team is investigating the issue on their end but having an extra set of eyes on it would be greatly appreciated.

[My Alexa skill](https://github.com/juliaqiuxy/slopeninja-backend/blob/master/src/api.js#L174-L180) is open source so feel free to fork it if you want to reproduce the issue.

**Comment by xs2bharat** [comment]
I just tested and its working fine with me. I only refereed function isValidSignature  from index.js only though. Rest i already had it working.

**Comment by pjryan93** [comment]
Is this still an ongoing issue? I don't want to disable testing from the console.

**Comment by mreinstein** [comment]
I don't have enough information to debug this problem. Can someone please provide more details, or let me know if this is working?

**Comment by pjryan93** [comment]
@mreinstein i believe this is fixed, from my testing.
