### ISSUE TITLE
Usage of validator module vulnerable version

### ISSUE THREAD

**Issue by mallikde-kore** [mreinstein/alexa-verifier#66]
### Issue:
validator package versions before 13.6.0 are vulnerable to ReDOS (Regular Expression Denial of Service) via isEmail and isHSL. The vulnerability can happen when checking if the crafted string is an email.

Suggestion:
Please update validator package to latest version to fix this vulnerability.

**Comment by dblock** [comment]
@mallikde-kore You could help by making a PR, please?

**Comment by mreinstein** [comment]
we don't use either of thoes validators, just `isBase64` so we should be ok. That said I'd still gladly update the package version if it doesn't break anything.
