### ISSUE TITLE
Feature request: easy middleware option

### ISSUE THREAD

**Issue by tejashah88** [mreinstein/alexa-verifier#8]
I wanted to suggest a feature that presents a middleware option for those who are using Express.js for their Alexa skill. You would still be able to keep the original functionality.

I've actually created a node module of my own called [alexa-verifier-middleware](https://github.com/tejashah88/alexa-verifier-middleware), which essentially wraps the function you've provided in the example into a module.

**Code Example**:
```javascript
var avm = require('alexa-verifier-middleware');
...
var app = express();
app.use(avm());
```

It would be nice if you can incorporate this feature into your module so that it would be easier for new developers to add request verification to their Alexa skills and I wouldn't need to maintain my module for the sake of simplicity.

**Comment by tejashah88** [comment]
@mreinstein thank you for the quick reply. I've already added a section regarding the middleware placement.

If you really wanted, I could submit a PR adding this feature to your module as well as any needed tests so that people would look for one module to use when adding request verification.

**Comment by mreinstein** [comment]
@tejashah88 I'm not sure I understand what you mean by adding this feature to my module. Why not just use the module you've already created (`alexa-verifier-middleware`), which wraps mine?

**Comment by tejashah88** [comment]
@mreinstein What I'm trying to say is that your module could provide a second option, so that people could choose the middleware option if they want it simple and easy, or they could use the custom option that's in your example, if they want to tweak a few things here and there.

Note that the field names are not final and are there for the sake of this example.
```javascript
var express  = require('express');
var alexa_verifier = require('alexa-verifier');
// this module would contain two fields, a reference to the 'verifier' function and a function
// which presents middleware that can be consumed by express

var app = express();

// middleware example
app.use(alexa_verifier.middleware());
//this would be the equivalent to my module's example: 'app.use(avm());'

// custom example
app.use(function(req, res, next) {
  if (!req.headers.signaturecertchainurl) {
    return next();
  }

  // mark the request body as already having been parsed so it's ignored by
  // other body parser middlewares
  req._body = true;
  req.rawBody = '';
  req.on('data', function(data) {
    return req.rawBody += data;
  });
  req.on('end', function() {
    var cert_url, er, error, requestBody, signature;
    try {
      req.body = JSON.parse(req.rawBody);
    } catch (error) {
      er = error;
      req.body = {};
    }
    cert_url = req.headers.signaturecertchainurl;
    signature = req.headers.signature;
    requestBody = req.rawBody;

    // 'verifier' would change to 'alexa_verifier.verifier'
    alexa_verifier.verifier(cert_url, signature, requestBody, function(er) {
      if (er) {
        console.error('error validating the alexa cert:', er);
        res.status(401).json({ status: 'failure', reason: er });
      } else {
        next();
      }
    });
  });
});
```

**Comment by mreinstein** [comment]
@tejashah88 I think the express middleware you've created is a good encapsulation. My plan is to remove all the express-specific stuff from my module, and update the README to point people at your module specifically for express support.

**Comment by mreinstein** [comment]
@tejashah88 I've sent you a PR that tweaks the documentation a little. It's a bit shorter and I added a few comments here and there. 

https://github.com/tejashah88/alexa-verifier-middleware/pull/1

Assuming you like these changes I'm happy to slim down my module and point people at yours for express related stuff.

thoughts?

**Comment by mreinstein** [comment]
great work man! I've moved all the express stuff out of the readme and point people at your module.

**Comment by tejashah88** [comment]
No problem, happy to help out!
